default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: muse-my-vinyls_development

test:
  <<: *default
  database: muse-my-vinyls_test

  production:
  <<: *default
  url: <%= ENV['POSTGRESQL_ADDON_URI'] %>
